version: "3"
services:
  backend:
    image: kgaurav8026/chatly-cicd_backend:latest
    ports:
      - "5000:5000"
    networks:
      - app-network

  frontend:
    image: kgaurav8026/chatly-cicd_frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
